kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nodo-bfa-core-fork
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nodo-bfa-core-fork:test'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://gitlab.bfa.ar/docker/bfanodo.git'
      ref: master
    contextDir: "bfatoolbase"  
    dockerfile: "FROM bfaar/nodo:test \nUSER root \nRUN chown 30303:0 ${BFAHOME} && chgrp -R 0 ${BFAHOME} && chmod -R g=u ${BFAHOME} \nUSER bfa"
  runPolicy: Serial 
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: bfadocker
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nodo-bfa:test'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/maximilianoPizarro/bfa.git'
      ref: main
    sourceSecret:
      name: gittoken      
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: hookbfa
  runPolicy: Serial
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: bfadocker-core
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nodo-bfa-core:test'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/maximilianoPizarro/bfa.git'
      ref: main
    contextDir: Dockerfile.core      
    sourceSecret:
      name: gittoken      
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: hookbfa
  runPolicy: Serial  

 