kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nodo-bfa
  labels:
    app: nodo-bfa
    app.kubernetes.io/component: nodo-bfa
    app.kubernetes.io/instance: nodo-bfa
    app.kubernetes.io/name: nodo-bfa
    app.kubernetes.io/part-of: nodo-bfa
spec:
  lookupPolicy:
    local: false
  tags:
    - name: test
      annotations:
        openshift.io/imported-from: 'bfaar/nodo:test'
      from:
        kind: DockerImage
        name: 'bfaar/nodo:test'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Local
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nodo-bfa-core
  labels:
    app: nodo-bfa
    app.kubernetes.io/component: nodo-bfa-core
    app.kubernetes.io/instance: nodo-bfa-core
    app.kubernetes.io/name: nodo-bfa-core
    app.kubernetes.io/part-of: nodo-bfa-core
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nodo-bfa-core-fork
  labels:
    app: nodo-bfa
    app.kubernetes.io/component: nnodo-bfa-core-fork
    app.kubernetes.io/instance: nodo-bfa-core-fork
    app.kubernetes.io/name: nnodo-bfa-core-fork
    app.kubernetes.io/part-of: nodo-bfa-core-fork    
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nodo-bfa-toolbase
spec:
  lookupPolicy:
    local: false
  tags:
    - name: toolbase
      annotations:
        openshift.io/imported-from: 'bfaar/nodo:toolbase'
      from:
        kind: DockerImage
        name: 'bfaar/nodo:toolbase'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: client-go
spec:
  lookupPolicy:
    local: false
  tags:
    - name: alltools-v1.9.11
      annotations:
        openshift.io/imported-from: 'ethereum/client-go:alltools-v1.9.11'
      from:
        kind: DockerImage
        name: 'ethereum/client-go:alltools-v1.9.11'
      generation: 4
      importPolicy: {}
      referencePolicy:
        type: Local
---        
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: solc
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 0.6.3-alpine
      annotations:
        openshift.io/imported-from: 'ethereum/solc:0.6.3-alpine'
      from:
        kind: DockerImage
        name: 'ethereum/solc:0.6.3-alpine'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Local        