kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: bfadocker
  namespace: mpizarro-dev
spec:
  nodeSelector: null
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: mpizarro-dev
        name: 'nodo-bfa:test'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://gitlab.bfa.ar/docker/bfanodo.git'
      ref: master
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial