kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: nodo-bfa
  labels:
    app: nodo-bfa
    app.kubernetes.io/component: nodo-bfa
    app.kubernetes.io/instance: nodo-bfa
    app.kubernetes.io/name: nodo-bfa
    app.openshift.io/runtime: golang
spec:
  replicas: 1
  selector:
    app: nodo-bfa
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodo-bfa
        deploymentconfig: nodo-bfa
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      restartPolicy: Always
      serviceAccountName: default
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - name: nodo-bfa
          image: >-
            image-registry.openshift-image-registry.svc:5000/mpizarro-dev/nodo-bfa@sha256:9714ebcf6f103c6c0fa710b50211308f7859f22c8c72f8606e1e694d35e179ff
          ports:
            - containerPort: 30303
              protocol: TCP
            - containerPort: 30303
              protocol: UDP
            - containerPort: 8545
              protocol: TCP
            - containerPort: 8546
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nodo-bfa-1
              mountPath: /HOME/BFA
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      serviceAccount: default
      volumes:
        - name: nodo-bfa-1
          persistentVolumeClaim:
            claimName: pvc-bfa
      dnsPolicy: ClusterFirst
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
